name: e_nusantara
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  filter_list: ^1.0.3
  buttons_tabbar: ^1.3.13
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.1
  flutter_icon_snackbar: ^1.2.1
  top_snackbar_flutter: ^3.1.0
  fan_carousel_image_slider: ^1.0.1
  intl: ^0.19.0
  flutter_popup_menu_button: ^0.0.1+5
  flutter_local_notifications: 14.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/

  fonts:
    - family: AbhayaLibre
      fonts:
        - asset: fonts/AbhayaLibre-Bold.ttf
          weight: 500
        - asset: fonts/AbhayaLibre-ExtraBold.ttf
          weight: 700
        - asset: fonts/AbhayaLibre-SemiBold.ttf
          weight: 600
        - asset: fonts/AbhayaLibre-Medium.ttf
          weight: 400
        - asset: fonts/AbhayaLibre-Regular.ttf
